package dev.reception.common.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import java.util.Objects;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * The identity half of every entity: an application-assigned UUID v7 primary key.
 *
 * <p>Because the id is assigned rather than generated by the database, Spring Data cannot tell a
 * new row from a detached one and would issue a SELECT before every INSERT. {@link Persistable}
 * answers the question directly, so {@code save()} on a new entity is one statement.
 *
 * <p>Equality is by id and is only meaningful once an id exists — which, here, is from
 * construction, since the application assigns it.
 */
@MappedSuperclass
public abstract class BaseEntity implements Persistable<UUID> {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Transient
    private boolean isNew = true;

    protected BaseEntity() {
        // JPA.
    }

    protected BaseEntity(UUID id) {
        this.id = Objects.requireNonNull(id, "id");
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markPersisted() {
        this.isNew = false;
    }

    @Override
    public final boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        // Hibernate proxies are subclasses, so getClass() comparison would reject a lazy reference
        // to the same row.
        if (!(other instanceof BaseEntity that)) {
            return false;
        }
        // getId() rather than the field: on a Hibernate proxy the field is not populated, but the
        // identifier getter is intercepted and answers without initialising the proxy.
        UUID thisId = getId();
        return thisId != null && thisId.equals(that.getId());
    }

    @Override
    public final int hashCode() {
        // Safe because the application assigns the id at construction, so it is set before an
        // entity can reach a hash-based collection and never changes afterwards. That is the
        // property that makes an id-based hash correct here and unsafe in a database-generated
        // scheme.
        UUID thisId = getId();
        return thisId == null ? 0 : thisId.hashCode();
    }
}
